name: arelle-web-service
version: 1.1.11
appVersion: 4.0.7
description: Arelle is a project to provide the XBRL community with an easy to use open source platform for XBRL.
keywords:
- arelle
- xbrl
- ixbrl
- us-gaap
- ifrs
home: http://arelle.org
icon:
sources:
- https://github.com/dfs-activedisclosure/arelle-web-service
maintainers:
- name: DFSCO
  email: adeng-all@dfsco.com
engine: gotpl
